version: "3"
services:

  go-cqhttp:
    build: ./go-cqhttp
    image: sjtu-plus/go-cqhttp:1.0
    volumes:
      - "./go-cqhttp-data:/data"
    depends_on:
      - nonebot

  nonebot:
    build: ./qbot
    expose:
      - "8080"
    environment:
      - TZ=Asia/Shanghai
      - ATTESTATION_SECRET=
    volumes:
      - "./qbot:/root/qbot"

  webserver:
    build: ./web
    ports:
      - 5000:5000
    volumes:
      - "./web:/root/web"
